### PR TITLE
Improved Project Deliverables

### PR DESCRIPTION
**Pull request by valentino-jaber**
HIIIII

### CODE REVIEW

**Comment by ressngu** [comment]
I approve c:

**Comment by HuskedCorn** [comment]
I think this is a great idea which could really help the team move forward

**Comment by Tailwiind** [comment]
very awesome

**Comment by KevinZhiyuanDing** [comment]
approve

**Review by KaiAsaoka — APPROVED** [review]
Wow, no way... approved :')

**Comment by HuskedCorn** [comment]
i no longer approve

**Review by seeeaaagull — APPROVED** [review]

**Review by Tailwiind — APPROVED** [review]
so awesome

**Review by JamesZhZhang — CHANGES_REQUESTED** [review]
Please change to a crying emoji 😭

**Review by KevinZhiyuanDing — APPROVED** [review]
Approve

**Review by ressngu — APPROVED** [review]
so beautiful 🌵

**Review by HuskedCorn — APPROVED** [review]

**Review by paigejh13 — APPROVED** [review]
Very heartfelt

**Review by HuskedCorn — APPROVED** [review]

**Review by JamesZhZhang — APPROVED** [review]
Thank you for adding the 😭emoji

**Pull request merged**
